name: GitGuardian scan

on: [push, pull_request]

jobs:
  ggshield:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for secrets with GitGuardian
        uses: GitGuardian/ggshield-action@v1.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
